
version: "3.0"
services:
  lpmonitor-sql:
    restart: always
    image: seapapa/postgres:10.18
    network_mode: host
    container_name: lpmonitor-sql
    volumes:
      - /etc/localtime:/etc/localtime
      - sql_data:/var/lib/postgresql/data

  lpmonitor-gui:
    restart: always
    image: seapapa/lpmonitor-gui:arm64_2.2
    network_mode: host
    container_name: lpmonitor-gui
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - $HOME:/data
      - /etc/localtime:/etc/localtime
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    depends_on:
      - lpmonitor-sql

  lpmonitor:
    restart: always
    image: seapapa/lpmonitor:arm64_2.2
    network_mode: host
    container_name: lpmonitor
    privileged: true
    volumes:
      - $HOME:/data
      - /dev/:/dev/
      - /etc/localtime:/etc/localtime
    depends_on:
      - lpmonitor-gui
    command:
      - "/root/lpmonitor"
      - "run"
      -  "-country"
      - "fr"
      - "-test"

volumes:
  sql_data:



